[package]
name = "bwserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log4rs = "1.2.0"
log = "0.4.17"
rand = "0.8.5"
